# Generated by Django 2.2 on 2019-04-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190417_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='core.Human'),
        ),
        migrations.AlterField(
            model_name='child',
            name='human',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='core.Human'),
        ),
        migrations.AlterField(
            model_name='human',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humans', to='core.Parent'),
        ),
    ]
