# Generated by Django 2.2 on 2019-04-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190418_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='human',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='core.Human'),
        ),
    ]
