# Generated by Django 2.2 on 2019-04-30 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190419_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='human',
        ),
        migrations.AddField(
            model_name='avatar',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatars', to='core.Parent'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='siblings',
            field=models.ManyToManyField(related_name='avatars', to='core.Sibling'),
        ),
    ]
