# Generated by Django 2.2 on 2019-05-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190430_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sibling',
            options={'verbose_name': 'Tagsss', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='avatars', to='core.Sibling'),
        ),
        migrations.AlterField(
            model_name='human',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='humans', to='core.Sibling'),
        ),
    ]
