# Generated by Django 2.2 on 2019-05-07 23:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190503_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='content',
            field=models.TextField(help_text='The description for the content, for example, the question detail or a blog post.'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The time the object created.'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The extra data for the object.'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The time the object modified.'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(help_text='The title/name for the content, for example, a title for a blog post.', max_length=256),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='parent',
            field=models.ForeignKey(help_text='A belongs_to relation to parent object, \n                               for example, a question belongs to a category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatars', to='core.Parent'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='siblings',
            field=models.ManyToManyField(blank=True, help_text='A many_to_many relation to siblings object, \n                                      for example, a question can have many tags', related_name='avatars', to='core.Sibling'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(help_text='The user who the object belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='child',
            name='content',
            field=models.TextField(help_text='The content for the object,\n                               for example, a commit content or an answer detail for the question', max_length=512),
        ),
        migrations.AlterField(
            model_name='child',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The time the object created.'),
        ),
        migrations.AlterField(
            model_name='child',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The extra data for the object.'),
        ),
        migrations.AlterField(
            model_name='child',
            name='human',
            field=models.ForeignKey(help_text='A belongs_to relation to human object, \n                              for example, an answer belongs to a question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='core.Human'),
        ),
        migrations.AlterField(
            model_name='child',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The time the object modified.'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, help_text='The title/name for the object, \n                            for example, a one line answer or a short answer summary.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.ForeignKey(help_text='The user who the object belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='human',
            name='content',
            field=models.TextField(help_text='The description for the content, for example, the question detail or a blog post.'),
        ),
        migrations.AlterField(
            model_name='human',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The time the object created.'),
        ),
        migrations.AlterField(
            model_name='human',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The extra data for the object.'),
        ),
        migrations.AlterField(
            model_name='human',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The time the object modified.'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(help_text='The title/name for the content, for example, a title for a blog post.', max_length=256),
        ),
        migrations.AlterField(
            model_name='human',
            name='parent',
            field=models.ForeignKey(help_text='A belongs_to relation to parent object, \n                               for example, a question belongs to a category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humans', to='core.Parent'),
        ),
        migrations.AlterField(
            model_name='human',
            name='siblings',
            field=models.ManyToManyField(blank=True, help_text='A many_to_many relation to siblings object, \n                                      for example, a question can have many tags', related_name='humans', to='core.Sibling'),
        ),
        migrations.AlterField(
            model_name='human',
            name='user',
            field=models.ForeignKey(help_text='The user who the object belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The time the object created.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The extra data for the object.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='description',
            field=models.CharField(help_text='The description for the object, for example, a category description.', max_length=256),
        ),
        migrations.AlterField(
            model_name='parent',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The time the object modified.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(help_text='The title/name for the object, for example, a category name.', max_length=64),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(help_text='The user who the object belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The time the object created.'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The extra data for the object.'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='description',
            field=models.CharField(help_text='The description for the object, for example, a tag description.', max_length=256),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The time the object modified.'),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='name',
            field=models.CharField(help_text='The title/name for the object, for example, a tag name.', max_length=64),
        ),
        migrations.AlterField(
            model_name='sibling',
            name='user',
            field=models.ForeignKey(help_text='The user who the object belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
